package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRealface<M extends BaseRealface<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setIsindoor(java.lang.Integer isindoor) {
		set("isindoor", isindoor);
		return (M)this;
	}

	public java.lang.Integer getIsindoor() {
		return get("isindoor");
	}

	public M setMoblietype(java.lang.String moblietype) {
		set("moblietype", moblietype);
		return (M)this;
	}

	public java.lang.String getMoblietype() {
		return get("moblietype");
	}

	public M setCreattime(java.util.Date creattime) {
		set("creattime", creattime);
		return (M)this;
	}

	public java.util.Date getCreattime() {
		return get("creattime");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}

	public java.lang.String getUrl() {
		return get("url");
	}

}
