package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseFakeface<M extends BaseFakeface<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setPid(java.lang.Integer pid) {
		set("pid", pid);
		return (M)this;
	}

	public java.lang.Integer getPid() {
		return get("pid");
	}

	public M setIsindoor(java.lang.Integer isindoor) {
		set("isindoor", isindoor);
		return (M)this;
	}

	public java.lang.Integer getIsindoor() {
		return get("isindoor");
	}

	public M setMobiletype(java.lang.String mobiletype) {
		set("mobiletype", mobiletype);
		return (M)this;
	}

	public java.lang.String getMobiletype() {
		return get("mobiletype");
	}

	public M setFaketype(java.lang.Integer faketype) {
		set("faketype", faketype);
		return (M)this;
	}

	public java.lang.Integer getFaketype() {
		return get("faketype");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public M setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
		return (M)this;
	}

	public java.util.Date getCreatetime() {
		return get("createtime");
	}

}
