package com.demo.common.model;

import com.demo.common.model.base.BaseFakeface;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Fakeface extends BaseFakeface<Fakeface> {
	public static final Fakeface dao = new Fakeface().dao();
}
