package com.demo.common.model;

import com.demo.common.model.base.BaseRealface;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Realface extends BaseRealface<Realface> {
	public static final Realface dao = new Realface().dao();
}
